name: iOS Build validation

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: macos-26

    steps:
        - uses: actions/checkout@v4

        - name: Select Xcode 26 (or latest)
          run: sudo xcode-select -switch /Applications/Xcode.app

        - name: Install SwiftLint
          run: brew install swiftlint

        - uses: xavierLowmiller/xcodegen-action@1.2.4
          with:
            spec: project.yml
            quiet: true
            version: '2.17.0'

        - name: Build
          run: xcodebuild clean build -project LOLLY.xcodeproj -scheme LOLLY 'platform=iOS Simulator,name=iPhone 17,OS=26.0'
            CODE_SIGNING_ALLOWED=NO

  swiftlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: GitHub Action for SwiftLint with --strict
        uses: norio-nomura/action-swiftlint@3.2.1
        with:
          args: --strict
