name: iOS Build validation

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: macos-26

    steps:
        - uses: actions/checkout@v4

        - name: Select Xcode
          run: sudo xcode-select -switch /Applications/Xcode.app

        - name: Install SwiftLint
          run: brew install swiftlint

        - name: Install SwiftGen
          run: brew install swiftgen

        - uses: xavierLowmiller/xcodegen-action@1.2.4
          with:
            spec: project.yml
            quiet: true
            version: '2.17.0'

        - name: Build target Brewsell
          run: |
            xcodebuild clean build \
            -project LOLLY.xcodeproj \
            -scheme Brewsell \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 17,OS=26.0.1' \
            CODE_SIGNING_ALLOWED=NO

        - name: Build target Harucha
          run: |
            xcodebuild clean build \
            -project LOLLY.xcodeproj \
            -scheme Harucha \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 17,OS=26.0.1' \
            CODE_SIGNING_ALLOWED=NO

